### ISSUE TITLE
Accessibility Issue: White Text on White Background in Dark Mode

### ISSUE THREAD

**Issue by mercqwe** [zerotohero-dev/zerotohero-web#1]
**What happened:**
On https://zerotohero.dev/vadideki-geyik/ when using dark mode, the texts with white background are hard to read because they are white as well.

**What is expected:**
The texts with white background should be color black.

![image](https://github.com/zerotohero-dev/zerotohero-web/assets/134650729/5c7a2292-0b18-44ce-9144-e2a3625f8f75)

**Comment by v0lkan** [comment]
Thanks for the report 🙏 .

**Comment by cansirin** [comment]
fixed with #7
